---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - git
    state: present

- name: Add Docker GPG apt Key
  ansible.builtin.shell: |
    timeout 10 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    executable: /bin/bash
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Download Docker Compose
  ansible.builtin.shell: |
    curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
  args:
    executable: /bin/bash
  become: true

- name: Set permissions for Docker Compose
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Python Docker SDK and Docker Compose
  apt:
    name: 
      - python3-docker
      - docker-compose
    state: present
    update_cache: yes

- name: Create docker network
  community.docker.docker_network:
    name: todo-network
    state: present